basic/urls.py
from django.conf.urls import url
from . import views

app_name = 'basic'

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^search/$', views.search, name='query'),
    url(r'^logout/$', views.logOut, name='logout'),
    url(r'^feedback/$', views.feed, name='feed'),
    url(r'^addmusic/$',views.addobject,name='addmusic'),
    url(r'^addmovie/$',views.addobject,name='addmovie'),
    url(r'^message/$', views.addobject, name='message'),
    url(r'^inbox/$', views.inbox, name='inbox'),
]

final/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^$', views.dawn, name='dawn'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),
    url(r'^basic/', include('basic.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/startbootstrap-agency-gh-pages/inbox.html
{% extends 'base.html' %}

{% block title %}
    Inbox
{% endblock %}

{% block body %}
    <div class="container">
        <table class="table">
            <tr>
                <th>Sender</th>
                <th>Message</th>
                <th>Time</th>
            </tr>
            {% if message %}
                {% for i in message %}
                    <tr>
                        <td>{{ i.sender }}</td>
                        <td>{{ i.message_text }}</td>
                        <td>{{ i.message_date }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <div style="text-align: center;"><p>No messages yet</p></div>
            {% endif %}
        </table>
    </div>
{% endblock %}

templates/startbootstrap-agency-gh-pages/include.html
<footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Your Website 2017</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

templates/startbootstrap-agency-gh-pages/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Shelf Life</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#team">Contact</a>
            </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'basic:message' %}">Message</a>
              </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'basic:logout' %}"><span class="glyphicon glyphicon-user"></span>Log out</a>
            </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'basic:query' %}"><span class="glyphicon glyphicon-search"></span>&nbsp;Search</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>

templates/startbootstrap-agency-gh-pages/popup.html
{% extends 'base.html' %}

{% block title %}
    Message
{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">
            <form method="post" action="{% url 'basic:message' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success">Send <span class="glyphicon glyphicon-send" type="submit"></span></button>
            </form>
        </div>
    </div>
{% endblock %}