basic/urls.py
from django.conf.urls import url
from . import views

app_name = 'basic'

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^search/$', views.search, name='query'),
    url(r'^logout/$', views.logOut, name='logout'),
    url(r'^feedback/$', views.feed, name='feed'),
    url(r'^addmusic/$',views.addobject,name='addmusic'),
    url(r'^addmovie/$',views.addobject,name='addmovie'),
    url(r'^message/$', views.addobject, name='message'),
    url(r'^inbox/$', views.inbox, name='inbox'),
]

final/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^$', views.dawn, name='dawn'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),
    url(r'^basic/', include('basic.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
    url(r'^$', views.FormView.as_view(), name='login'),
    url(r'^sign/$', views.SignUp.as_view(), name='sign'),
]

login/models.py
# empty file

login/forms.py
from django.contrib.auth.admin import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

login/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import authenticate, login


class FormView(View):
    form_class = UserForm
    template_name = 'form-login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        usr = authenticate(username=username, password=password)
        if usr is not None:
            login(request, usr)
            return redirect('basic:index')
        else:
            return render(request, 'form-login.html', {'message': "Either username or password is not valid"})


class SignUp(View):
    form_class = UserForm
    template_name = 'form-register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        again = request.POST['again']

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            if again != password:
                return render(request, 'form-register.html', {'message': "password fields don't match"})

            user.set_password(password)

            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('basic:index')
                else:
                    return render(request, 'form-register.html', {'message': "user not active"})
            else:
                return render(request, 'form-register.html', {'message': "user is not authenticated"})
        else:
            return render(request, 'form-register.html', {'message': "username already exist"})

templates/addmovie_html.html
<html>
<head>
<title>
Movie Eros
</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% load staticfiles %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>
ul {
    list-style-type: none;
    margin:0;
    padding: 0px;
    overflow: hidden;
	width:100%;
    background-color: #333;
}
li {
    float: left;
}

li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
    background-color: black;
}

li.dropdown {
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #333;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: white;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}

.dropdown-content a:hover {background-color: black}

.dropdown:hover .dropdown-content {
    display: block;
}
#contact-form {
    background-color: rgba(72,72,72,0.7);
    padding: 10px 20px 30px 20px;
    max-width: 100%;
    float: left;
    left: 50%;
    position: relative;
    margin-top: 30px;
    margin-left: -260px;
    border-radius: 7px;
    -webkit-border-radius: 7px;
    -moz-border-radius: 7px;
}

body{
	margin:0;
	padding:0;
    background-position: center center;
    width: 100%;
    height: 100%;

	/*overflow: hidden;*/
	/*clear:both;*/
	}
input[type=text], select {
    width: 100%;
	background-color:white;
    padding: 12px 20px;
    margin: 8px ;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=submit] {
    align:center;
	width: 60%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    /*margin-top: 4px ;*/
	margin-left: 55px ;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}
.bg-form{
margin: auto;
}
.in{
position: absolute;

width: 100%;
height:100%;
background-position:center center;
}

#frm{

/*background-color: rgba(72,72,72,10);*/
    padding: 20px 30px 10px 20px;
    left: 8%;
    position: absolute;
	width:25%;
	height:75%;
    border-radius: 12px;
	border-style:solid;
	border-width: 1px;
    background-color: #f2f2f2;

}
</style>
</head>
<body background="{% static '11.jpg' %}" >
<ul position="fixed">
<li >
	<a href="#ShellLife">ShellLife</a></li>
  <li>
  <a href="{% url 'basic:index' %}">Home</a></li>
  <li ><a href="#news">Profile</a></li>
  <li class="dropdown">
    <a href="#" class="dropbtn">Shelf</a>
    <div class="dropdown-content">
      <a href="{% url 'basic:addmusic' %}">Music</a>
      <a href="#">Pics</a>
      <a href="#">Videos</a>
	  <a href="#">News</a>
    </div>
	<li style="float:right"><a class="active" href="#about">Log Out</a></li>
  </li>
</ul>

<div class="in">
<div id="frm" style="margin-top: 9%;" class="bg-form">
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
	<br><input type="submit" value="Submit">
  </form>
</div>
</div>
</body>
</html>

templates/addmusic_html.html
<html>
<head>
<title>
Music Eros
</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% load staticfiles %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>
ul {
    list-style-type: none;
    margin:0;
    padding: 0px;
    overflow: hidden;
	width:100%;
    background-color: #333;
}
li {
    float: left;
}

li a, .dropbtn {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
    background-color: black;
}

li.dropdown {
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #333;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: white;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}

.dropdown-content a:hover {background-color: black}

.dropdown:hover .dropdown-content {
    display: block;
}
#contact-form {
    background-color: rgba(72,72,72,0.7);
    padding: 10px 20px 30px 20px;
    max-width: 100%;
    float: left;
    left: 50%;
    position: relative;
    margin-top: 30px;
    margin-left: -260px;
    border-radius: 7px;
    -webkit-border-radius: 7px;
    -moz-border-radius: 7px;
}

body{
	margin:0;
	padding:0;
	/*overflow: hidden;*/
	/*clear:both;*/
	}
input[type=text], select {
    width: 100%;
	background-color:white;
    padding: 12px 20px;
    margin: 8px ;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=submit] {
    align:center;
	width: 60%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    /*margin-top: 4px ;*/
	margin-left: 55px ;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}
.bg-form{
margin: auto;
}
.in{
position: absolute;

width: 100%;
height:100%;
background-position:center center;
}

#frm{

/*background-color: rgba(72,72,72,10);*/
    padding: 20px 30px 10px 20px;
    left: 8%;
    position: absolute;
	width:25%;
	height:75%;
    border-radius: 12px;
	border-style:solid;
	border-width: 1px;
    background-color: #f2f2f2;

}
</style>
</head>
<body background="{% static '4.jpg' %}">
<ul position="fixed">
<li >
	<a href="#ShellLife">ShellLife</a></li>
  <li>
  <a href="#home">Home</a></li>
  <li ><a href="#news">Profile</a></li>
  <li class="dropdown">
    <a href="#" class="dropbtn">Shelf</a>
    <div class="dropdown-content">
      <a href="#">Music</a>
      <a href="#">Pics</a>
      <a href="#">Videos</a>
	  <a href="#">News</a>
    </div>
	<li style="float:right"><a class="active" href="#about">Log Out</a></li>
  </li>
</ul>

<div class="in">
<div id="frm" style="margin-top: 9%;" class="bg-form">
  <form method="post" action="{% url 'basic:addmusic' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
	<br><input type="submit" value="Submit">
  </form>
</div>
</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ShelfLife</title>
    {% load staticfiles %}
    <link rel="icon" type="image/plain" href="{% static 'icon.png' %}">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{% block title %}{% endblock %}</title>

	<link rel="stylesheet" href="{% static 'assets/form-login.css' %}">
    <link rel="stylesheet" href="{% static 'assets/form-register.css' %}">
    <link rel="stylesheet" href="{% static 'assets/form-search.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="margin-bottom: 20px">
        <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'basic:index'%}">ShelfLife</a>
        </div>
        </div>
    </nav>
    <div style="margin-top: 80px" class="container">
    {% block body %}
    {% endblock %}
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand">© ShelfLife- All rights reserved</a>
        </div>
        </div>
    </nav>
    <script src="{% static 'dist/js/bootstrap.js' %}"></script>
</body>
</html>

templates/form-labels-on-top.html
<!DOCTYPE html>
<html>

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Form With Labels On Top</title>

	<link rel="stylesheet" href="../static/assets/demo.css">
	<link rel="stylesheet" href="../static/assets/form-labels-on-top.css">

</head>


	<header>
		<h1>Freebie: 7 Clean and Responsive Forms</h1>
        <a href="http://tutorialzine.com/2015/07/freebie-7-clean-and-responsive-forms/">Download</a>
    </header>

    <ul>
        <li><a href="index.html">Basic</a></li>
        <li><a href="form-register.html">Register</a></li>
        <li><a href="form-login.html">Login</a></li>
        <li><a href="form-mini.html">Mini</a></li>
        <li><a href="form-labels-on-top.html" class="active">Labels on Top</a></li>
        <li><a href="form-validation.html">Validation</a></li>
        <li><a href="form-search.html">Search</a></li>
    </ul>


    <div class="main-content">

        <!-- You only need this form and the form-labels-on-top.css -->

        <form class="form-labels-on-top" method="post" action="#">

            <div class="form-title-row">
                <h1>Form Example</h1>
            </div>

            <div class="form-row">
                <label>
                    <span>Full name</span>
                    <input type="text" name="name">
                </label>
            </div>

            <div class="form-row">
                <label>
                    <span>Email</span>
                    <input type="email" name="email">
                </label>
            </div>

            <div class="form-row">
                <label>
                    <span>Dropdown</span>
                    <select name="dropdown">
                        <option>Option One</option>
                        <option>Option Two</option>
                        <option>Option Three</option>
                        <option>Option Four</option>
                    </select>
                </label>
            </div>

            <div class="form-row">
                <label>
                    <span>Checkbox</span>
                    <input type="checkbox" name="checkbox" checked>
                </label>
            </div>

            <div class="form-row">
                <label><span>Radio</span></label>
                <div class="form-radio-buttons">

                    <div>
                        <label>
                            <input type="radio" name="radio">
                            <span>Radio option 1</span>
                        </label>
                    </div>

                    <div>
                        <label>
                            <input type="radio" name="radio">
                            <span>Radio option 2</span>
                        </label>
                    </div>

                    <div>
                        <label>
                            <input type="radio" name="radio">
                            <span>Radio option 3</span>
                        </label>
                    </div>

                </div>
            </div>

            <div class="form-row">
                <button type="submit">Submit Form</button>
            </div>

        </form>

    </div>

</body>

</html>

templates/form-login.html
{% extends 'base.html' %}
{% block body %}
        <form class="form-login" method="post" action="{% url 'login:login' %}">
        {% csrf_token %}
            <div class="form-log-in-with-email">

                <div class="form-white-background">

                    <div class="form-title-row">
                        <h1>Log in</h1>
                    </div>

                    <div class="form-row">
                        <label>
                            <span>Username</span>
                            <input type="text" name="username">
                        </label>
                    </div>

                    <div class="form-row">
                        <label>
                            <span>Password</span>
                            <input type="password" name="password">
                        </label>
                    </div>

                    <div class="form-row">
                        <button type="submit">Log in</button>
                    </div>
                </div>
                <a href="{% url 'login:sign' %}" class="form-create-an-account">Create an account &rarr;</a>
            </div>
        </form>
{% endblock %}
{% block title %}
    Sign Up
{% endblock %}

templates/form-mini.html
<!DOCTYPE html>
<html>

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Mini Form</title>

	<link rel="stylesheet" href="../static/assets/demo.css">
	<link rel="stylesheet" href="../static/assets/form-mini.css">

</head>


	<header>
		<h1>Freebie: 7 Clean and Responsive Forms</h1>
        <a href="http://tutorialzine.com/2015/07/freebie-7-clean-and-responsive-forms/">Download</a>
    </header>

    <ul>
        <li><a href="index.html">Basic</a></li>
        <li><a href="form-register.html">Register</a></li>
        <li><a href="form-login.html">Login</a></li>
        <li><a href="form-mini.html" class="active">Mini</a></li>
        <li><a href="form-labels-on-top.html">Labels on Top</a></li>
        <li><a href="form-validation.html">Validation</a></li>
        <li><a href="form-search.html">Search</a></li>
    </ul>


    <div class="main-content">

        <!-- You only need this form and the form-mini.css -->

        <div class="form-mini-container">


            <h1>Mini Form</h1>

            <form class="form-mini" method="post" action="#">

                <div class="form-row">
                    <input type="text" name="name" placeholder="Your Name">
                </div>

                <div class="form-row">
                    <input type="email" name="email" placeholder="Your Email">
                </div>

                <div class="form-row">
                    <label>
                        <select name="dropdown">
                            <option>Choose an option</option>
                            <option>Option One</option>
                            <option>Option Two</option>
                            <option>Option Three</option>
                            <option>Option Four</option>
                        </select>
                    </label>
                </div>

                <div class="form-row">
                    <label class="form-checkbox">
                        <input type="checkbox" name="checkbox" checked>
                        <span>Checkbox</span>
                    </label>
                </div>

                <div class="form-row">
                    <div class="form-radio-buttons">

                        <div>
                            <label>
                                <input type="radio" name="radio">
                                <span>Radio option 1</span>
                            </label>
                        </div>

                        <div>
                            <label>
                                <input type="radio" name="radio">
                                <span>Radio option 2</span>
                            </label>
                        </div>

                        <div>
                            <label>
                                <input type="radio" name="radio">
                                <span>Radio option 3</span>
                            </label>
                        </div>

                    </div>
                </div>

                <div class="form-row form-last-row">
                    <button type="submit">Submit Form</button>
                </div>

            </form>
        </div>


    </div>

</body>

</html>

templates/form-register.html
{% extends 'base.html' %}
{% block body %}
        <form class="form-register" method="post" action="{% url 'login:sign' %}">
            {% csrf_token %}
            <div class="form-register-with-email">
                <div class="form-white-background">

                    <div class="form-title-row">
                        <h1>Create an account</h1>
                    </div>

                    <div class="form-row">
                        <label>
                            <span>Username</span>
                            <input type="text" name="username">
                        </label>
                    </div>

                    <div class="form-row">
                        <label>
                            <span>Password</span>
                            <input type="password" name="password">
                        </label>
                    </div>

                    <div class="form-row">
                        <label>
                            <span>Password Again</span>
                            <input type="password" name="again">
                        </label>
                    </div>

                    <div class="form-row">
                        <label class="form-checkbox">
                            <input type="checkbox" name="checkbox" checked>
                            <span>I agree to the <a href="#">terms and conditions</a></span>
                        </label>
                    </div>

                    <div class="form-row">
                        <button type="submit">Register</button>
                    </div>

                </div>

                <a href="{% url 'login:login' %}" class="form-log-in-with-existing">Already have an account? Login here &rarr;</a>

            </div>

        </form>
{% endblock %}
{% block title %}
    Login
{% endblock %}

templates/form-search.html
{% extends 'base.html' %}
{% block body %}
    <div class="main-content" style="margin-bottom: 3%;margin-top: 3%">

        <!-- You only need this form and the form-search.css -->

        <form class="form-search" method="post" action="{% url 'basic:query' %}">
            {% csrf_token %}
            <input type="search" name="query" value="{{ value }}" placeholder="I am looking for..">
            <button type="submit">Search</button>
            <i class="fa fa-search"></i>
        </form>
    </div>
    {% for i in get %}
    <div class="jumbotron">
        <center><h1><strong>{{ i }}</strong></h1></center>
    </div>
    {% endfor %}

{% endblock %}
{% block title %}
    Search
{% endblock %}

templates/form-validation.html
<!DOCTYPE html>
<html>

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Validation Form</title>

	<link rel="stylesheet" href="../static/assets/demo.css">
	<link rel="stylesheet" href="../static/assets/form-validation.css">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

</head>


	<header>
		<h1>Freebie: 7 Clean and Responsive Forms</h1>
        <a href="http://tutorialzine.com/2015/07/freebie-7-clean-and-responsive-forms/">Download</a>
    </header>

    <ul>
        <li><a href="index.html">Basic</a></li>
        <li><a href="form-register.html">Register</a></li>
        <li><a href="form-login.html">Login</a></li>
        <li><a href="form-mini.html">Mini</a></li>
        <li><a href="form-labels-on-top.html">Labels on Top</a></li>
        <li><a href="form-validation.html" class="active">Validation</a></li>
        <li><a href="form-search.html">Search</a></li>
    </ul>


    <div class="main-content">

        <!-- You only need this form and the form-validation.css -->

        <form class="form-validation" method="post" action="#">

            <div class="form-title-row">
                <h1>Form Validation</h1>
            </div>

            <div class="form-row form-input-name-row">

                <label>
                    <span>Full name</span>
                    <input type="text" name="name">
                </label>

                <!--
                    Add these three elements to every form row. They will be shown by the
                    .form-valid-data and .form-invalid-data classes (see the JS for an example).
                -->

                <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>

                <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
                <span class="form-invalid-data-info"></span>

            </div>

            <div class="form-row form-input-email-row">

                <label>
                    <span>Email</span>
                    <input type="email" name="email" value="email@example.com">
                </label>

                <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>

                <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
                <span class="form-invalid-data-info"></span>

            </div>

            <div class="form-row">

                <label>
                    <span>Dropdown</span>
                    <select name="dropdown">
                        <option>Choose an option</option>
                        <option>Option One</option>
                        <option>Option Two</option>
                        <option>Option Three</option>
                        <option>Option Four</option>
                    </select>
                </label>

            </div>

            <div class="form-row">

                <label class="form-checkbox">
                    <span>Checkbox</span>
                    <input type="checkbox" name="checkbox" checked>
                </label>

            </div>

            <div class="form-row">

                <button type="submit">Submit Form</button>

            </div>

        </form>

    </div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>

    $(document).ready(function() {

        // Here is how to show an error message next to a form field

        var errorField = $('.form-input-name-row');

        // Adding the form-invalid-data class will show
        // the error message and the red x for that field

        errorField.addClass('form-invalid-data');
        errorField.find('.form-invalid-data-info').text('Please enter your name');


        // Here is how to mark a field with a green check mark

        var successField = $('.form-input-email-row');

        successField.addClass('form-valid-data');
    });

</script>

</body>

</html>

templates/login_form.html
{% extends 'base.html' %}

{% block body %}
    <div class="page-header">
        <h1 style="font-family: SansSerif">Login</h1>
    </div>
    <form action="{% url 'login:login' %}" method="post" style="margin-bottom: 2%">
        {% csrf_token %}
        <div class="input-group" style="margin-bottom: 2%">
            <h1 class="input-group-addon">Name </h1><input class="form-control" name="username" width="20px">
        </div>
        <div class="input-group" style="margin-bottom: 2%">
            <h1 class="input-group-addon">Password</h1><input class="form-control" type="password" name="password">
        </div>
        <input class="btn btn-success btn-lg" type="submit">
    </form>
    <a href="{% url 'login:sign'%}" style="margin-bottom: 50px">Not Registered</a>
    {% if message %}
        <h1 class="fa-bold">{{ message }}</h1>
    {% endif %}
{% endblock %}

templates/main.html
<div class="container">
  <form id="contact" action="" method="post">
    <h3>Colorlib Contact Form</h3>
    <h4>Contact us for custom quote</h4>
    <fieldset>
      <input placeholder="Your name" type="text" tabindex="1" required autofocus>
    </fieldset>
    <fieldset>
      <input placeholder="Your Email Address" type="email" tabindex="2" required>
    </fieldset>
    <fieldset>
      <input placeholder="Your Phone Number (optional)" type="tel" tabindex="3" required>
    </fieldset>
    <fieldset>
      <input placeholder="Your Web Site (optional)" type="url" tabindex="4" required>
    </fieldset>
    <fieldset>
      <textarea placeholder="Type your message here...." tabindex="5" required></textarea>
    </fieldset>
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
    <p class="copyright">Designed by <a href="https://colorlib.com" target="_blank" title="Colorlib">Colorlib</a></p>
  </form>
</div>

templates/search.html
{% extends 'base.html' %}

{% block body %}
    <form id="content" method="post" action="{% url 'basic:query' %}" class="input-group">
        {% csrf_token %}
        <div class="jumbotron">
            <table border="0" align="center" cellpadding="0">
            <tr>
            <input class="form-control" type="text"   name="query" size="25" style="color:#808080;"
                    maxlength="255" placeholder="Search Site Here"
                    />
                <p>&nbsp;</p>
            </tr>
            </table>
        </div>
    </form>
    <div>
        {% for i in get %}
            <div class="result" style="fill: lightblue">
                <h4>{{ i }}</h4>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block body %}
    <div class="page-header">
        <h1>Sign Up</h1>
    </div>
    <form action="{% url 'login:sign' %}" method="post" style="margin-bottom: 2%">
        {% csrf_token %}
        <div class="input-group" style="margin-bottom: 2%">
            <h1 class="input-group-addon">Name </h1><input class="form-control" name="username" width="20px">
        </div>
        <div class="input-group" style="margin-bottom: 2%">
            <h1 class="input-group-addon">Password</h1><input class="form-control" type="password" name="password">
        </div>
        <div class="input-group" style="margin-bottom: 2%">
            <h1 class="input-group-addon">Password (again) </h1><input class="form-control" type="password" name="again">
        </div>
        <input class="btn btn-default btn-lg" type="submit">
    </form>
    {% if message %}
        <h1 class="fa-bold">{{ message }}</h1>
    {% endif %}
{% endblock %}